"""Add user roles

Revision ID: 96dee378d721
Revises: dc74e195309b
Create Date: 2025-07-07 23:14:58.747892

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "96dee378d721"
down_revision: Union[str, Sequence[str], None] = "dc74e195309b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_role_enum = sa.Enum("USER", "ADMIN", name="userrole")


def upgrade() -> None:
    """Upgrade schema."""
    user_role_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role", user_role_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
    user_role_enum.drop(op.get_bind())
